### ISSUE TITLE
Hey guy

### ISSUE THREAD

**Issue by keery** [blaadje/vue-grids-layout#1]
```
Package vue-grid doesn't exists ...
```
What can I do ? I need your help plz 🤷‍♀️

**Comment by blaadje** [comment]
Hello @keery, documentation is still in progress but for now you can follow such an example : https://codesandbox.io/s/94kn30v8qy
where you can obv see that you should import `vue-grids-layout` 😄

**Comment by keery** [comment]
Indeed I forgot to import it.
Thx for your help
XOXO
